camel.health.enabled=true
camel.health.exposure-level=full
camel.karavan.project-id=Harkkatyö
camel.karavan.project-name=Harkkatyö
camel.karavan.target=none
camel.jbang.gav=com.example:harkkatyo:1.0.0
camel.jbang.quarkusVersion=3.15.3
camel.jbang.runtime=quarkus
camel.jbang.exportDir=.export