camel.health.enabled=true
camel.health.exposure-level=full
camel.karavan.project-id=HarkkatyÃ¶
camel.karavan.project-name=HarkkatyÃ¶
camel.karavan.target=none
quarkus.native.resources.includes=camel/integration.camel.yaml
